name: 'PR - Terraform Plan DEV'

on:
  push:
    branches:
       - '*'
       - '*/*'
       - '**'
       - '!main'  
  pull_request:
    branches:
       - '!main'  
jobs:
  terraform:
    name: 'PR Raise From Any Branch to Main'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.NIHR_DEVELOPMENT_IAM_ACCESS_KEY_SECRET }}
        aws-region: eu-west-2
    - name: Checkout
      uses: actions/checkout@v3

    - name: Terraform Init
      run: |
           terraform init -backend-config="bucket=${{ secrets.NIHR_DEV_TERRAFORM_BUCKET }}" -backend-config="key=rddi-study-management/dev/terraform.tfstate"
        
    - name: Terraform Validate
      run: |
           terraform validate

    - name: Terraform Format
      run: |
           terraform fmt

    - name: Terraform Plan
      run: |
           terraform plan -var="env=dev" 